services:
  web:
    container_name: web
    image: ghcr.io/bob-park/on-time-resources-management-web
    build:
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
